version = 0.1
[jpw-dev]
[jpw-dev.deploy]
[jpw-dev.deploy.parameters]
stack_name = "gonet-image-split"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mrokmiz3exit"
s3_prefix = "gonet-image-split"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"prod\" ImageSourceBucketName=\"gonet-image-source\" JpgOutputBucketName=\"gonet-split-jpeg\" TiffOutputBucketName=\"gonet-split-tiff\""
image_repositories = []

[adler-prod]
[adler-prod.deploy]
[adler-prod.deploy.parameters]
stack_name = "gonet-image-split-cat"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sfjet4i8q093"
s3_prefix = "gonet-image-split-cat"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"prod\" ImageSourceBucketName=\"gonet\" JpgOutputBucketName=\"gonet.split.jpeg\" TiffOutputBucketName=\"gonet.split.tiff\""
image_repositories = []
