version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gonet-image-split"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mrokmiz3exit"
s3_prefix = "gonet-image-split"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ENV=\"prod\" ImageSourceBucketName=\"gonet-image-source\" JpgOutputBucketName=\"gonet-split-jpeg\" TiffOutputBucketName=\"gonet-split-tiff\""
